---
- name: Install Sysmon
  hosts: windows
  vars:
      path: C:\agents\sysmon
  become_method: pwsh
  tasks:
      - name: Create directory to download sysmon package
        win_file:
          path: "{{path}}"
          state: directory

      - name: Add user ownership to this directory
        win_owner:
          path: "{{path}}"
          user: ansible
          recurse: true

      - name: Download installer zip file
        ansible.windows.win_get_url:
          url: https://github.com/AnupamRoy2191/Agent_installation/blob/main/Sysmon.zip
          dest: "{{path}}"
          checksum: 5968a22f9d51cfa30a1230d871b715c75db6bcbd1c1e4a2a69c78d07ed36795ffc752547556fc3bc38f01c3b85354f4f469cca3c3476d6452c45d254948eedd5
          checksum_algorithm: sha512

      - name: Unzip installer zip file
        community.windows.win_unzip:
          src: "{{path}}\\Sysmon.zip"
          dest: "{{path}}"

      - name: Install sysmon package
        win_shell: sysmon -accepteula -i
        args:
          chdir: "{{path}}"
      
      - name: Check sysmon service installation status
        win_shell: Get-service -Name sysmon


